server:
  port: 8080
  servlet:
    context-path: /luizalabs
    encoding:
      charset: UTF-8

springfox:
  documentation:
    swagger-ui:
      enabled: true
    open-api:
      enabled: true  
    swagger:
      v2:
        enabled: true

spring:
  datasource: 
    url: jdbc:mysql://localhost/Luizalabs
    username: magalu
    password: magalu
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: update


